version: "2"
services:
   mongodb:
      extends:
        file: mdb_base.yaml
        service: mongodb_switch_service
      command: mongos --configdb mongodb_config1_1:27017,mongodb_config2_1:27017,mongodb_config3_1:27017
      environment:
        - "constraint:node==${MACHINE0}"     
   rs1a:
     extends:
       file: mdb_base.yaml
       service: mongodb_service_replset_1
     volumes: 
       - /data/db/s1rs1a:/data/db
     environment:
        - "constraint:node==${MACHINE1}" 

   rs1b:
     extends:
       file: mdb_base.yaml
       service: mongodb_service_replset_1
     volumes: 
       - /data/db/s1rs1b:/data/db
     environment:
        - "constraint:node==${MACHINE2}" 

   rs1c:
     extends:
       file: mdb_base.yaml
       service: mongodb_service_replset_1
     volumes: 
       - /data/db/s1rs1c:/data/db
     environment:
        - "constraint:node==${MACHINE3}" 

   rs2a:
     extends:
       file: mdb_base.yaml
       service: mongodb_service_replset_2
     volumes: 
       - /data/db/s2rs2a:/data/db
     environment:
        - "constraint:node==${MACHINE4}" 

   rs2b:
     extends:
       file: mdb_base.yaml
       service: mongodb_service_replset_2
     volumes: 
       - /data/db/s2rs2b:/data/db
     environment:
        - "constraint:node==${MACHINE5}"

   rs2c:
     extends:
       file: mdb_base.yaml
       service: mongodb_service_replset_2
     volumes: 
       - /data/db/s2rs2c:/data/db
     environment:
        - "constraint:node==${MACHINE6}"

   config1:
     extends:
       file: mdb_base.yaml
       service: mongodb_config_service
     volumes: 
       - /data/db/config1:/data/db
     environment:
        - "constraint:node==${MACHINE0}"

   config2:
     extends:
       file: mdb_base.yaml
       service: mongodb_config_service
     volumes: 
       - /data/db/config2:/data/db
     environment:
       - "constraint:node==${MACHINE6}"

   config3:
     extends:
       file: mdb_base.yaml
       service: mongodb_config_service
     volumes: 
       - /data/db/config3:/data/db
     environment:
       - "constraint:node==${MACHINE5}"

networks:
  default:
    external:
      name: mongonet
