version: "2"
services:
  mongodb:
    extends:
      file: mdb_dev_cluster.yaml
      service: mongodb
    image: alvinr/mongos:latest
    environment:
      - "constraint:node==$SWARM0"

  rs1a:
    extends:
      file: mdb_dev_cluster.yaml
      service: rs1a
    image: mongo:$MONGO_VERSION
    environment:
      - "affinity:mongodb.mongod.replset!=rs1"
      - "constraint:node!=$SWARM0"

  rs1b:
    extends:
      file: mdb_dev_cluster.yaml
      service: rs1b
    image: mongo:$MONGO_VERSION
    environment:
      - "affinity:mongodb.mongod.replset!=rs1"
      - "constraint:node!=$SWARM0"

  rs1c:
    extends:
      file: mdb_dev_cluster.yaml
      service: rs1c
    image: mongo:$MONGO_VERSION
    environment:
      - "affinity:mongodb.mongod.replset!=rs1"
      - "constraint:node!=$SWARM0"

  rs2a:
    extends:
      file: mdb_dev_cluster.yaml
      service: rs2a
    image: mongo:$MONGO_VERSION
    environment:
      - "affinity:mongodb.mongod.replset!=rs2"
      - "constraint:node!=$SWARM0"

  rs2b:
    extends:
      file: mdb_dev_cluster.yaml
      service: rs2b
    image: mongo:$MONGO_VERSION
    environment:
      - "affinity:mongodb.mongod.replset!=rs2"
      - "constraint:node!=$SWARM0"

  rs2c:
    extends:
      file: mdb_dev_cluster.yaml
      service: rs2c
    image: mongo:$MONGO_VERSION
    environment:
      - "affinity:mongodb.mongod.replset!=rs2"
      - "constraint:node!=$SWARM0"

  config1:
    extends:
      file: mdb_dev_cluster.yaml
      service: config1
    image: mongo:$MONGO_VERSION
    environment:
      - "affinity:mongodb.role!=mongoc"
      - "constraint:node!=$SWARM0"

  config2:
    extends:
      file: mdb_dev_cluster.yaml
      service: config2
    image: mongo:$MONGO_VERSION
    environment:
      - "affinity:mongodb.role!=mongoc"
      - "constraint:node!=$SWARM0"

  config3:
    extends:
      file: mdb_dev_cluster.yaml
      service: config3
    image: mongo:$MONGO_VERSION
    environment:
      - "affinity:mongodb.role!=mongoc"
      - "constraint:node!=$SWARM0"
